name: Build and Push to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python and Checkout Code
        uses: actions/checkout@v4
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r app/requirements.txt

      - name: Set credentials file
        run: echo ${{ GCLOUD_CREDENTIALS }} > gcloud-credentials.json

      - name: Authenticate with Google Cloud
        run: gcloud auth activate-service-account --key-file="gcloud-credentials.json" --quiet

      - name: Build Docker image
        run: docker buildx build -t "api-image" .

      - name: Push Docker image to Artifact Registry
        env:
          COMMIT_HASH: ${{ GITHUB_SHA }}
        run: |
          docker tag "api-image" "us-central1-docker.pkg.dev/swift-doodad-413915/images/api:$COMMIT_HASH"
          docker push "us-central1-docker.pkg.dev/swift-doodad-413915/images/api:$COMMIT_HASH"

      - name: Run Terraform 
        env:
          COMMIT_HASH: ${{ GITHUB_SHA }}
        run: |
          terraform init
          terraform apply -auto-approve -var commit_hash=$COMMIT_HASH
