name: Build and Push to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r app/requirements.txt

      - name: Set credentials file
        env: 
          GOOGLE_CREDENTIALS: ${{ secrets.GCLOUD_CREDENTIALS }}
        run: echo $GOOGLE_CREDENTIALS > gcloud-credentials.json

      - name: Authenticate with Google Cloud and configure Docker
        run: |
          gcloud auth activate-service-account --key-file="gcloud-credentials.json" --quiet
          gcloud auth configure-docker "us-central1-docker.pkg.dev" --quiet

      - name: Build Docker image
        run: docker buildx build -t "api-image" .

      - name: Push Docker image to Artifact Registry
        run: |
          docker tag "api-image" "us-central1-docker.pkg.dev/swift-doodad-413915/images/api:${{ github.sha }}"
          docker push "us-central1-docker.pkg.dev/swift-doodad-413915/images/api:${{ github.sha }}"

      - name: Run Terraform 
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.CREDENTIALS_GCLOUD }}
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve -var commit_hash=${{ github.sha }}
